### PR TITLE
Fixed reverse copy and the expected result

### PR DESCRIPTION
**Pull request by pjbgtnj**
The expected value for reverse copy was incorrect.  After correction, the algorithm needed to be changed.  Either the for loop could be changed to "i <= j" or the algorithm could be changed.  I elected to change the algorithm slightly because after benchmarking - this version is faster, the code is clearer to read.

### CODE REVIEW

**Comment by tammersaleh** [comment]
#16 has a _slightly_ more performant algorithm (n/2 vs n), but this solution is much more readable and understandable.

**Comment by tammersaleh** [comment]
Thanks again for the PR!

**Comment by pjbgtnj** [comment]
No problem.  I didn't see any examples of benchmarks otherwise I would have
shared the benchmark code I wrote to test the various forms.  The n/2 case
was the slowest of all the versions I tried (I tested larger arrays).  In
the case where you're copying over the same array it makes sense to do the
swap trick (1/2 the number of cache line accesses) but when it's two
different arrays you're not likely saving any cache line accesses unless
the array is very small.

**Comment by tammersaleh** [comment]
huh - I guess I just assumed that running the loop half the times would be more performant, but I should have measured that before I put it in writing.  I removed that bit of text.

**Pull request merged**
